### ISSUE TITLE
After injecting process, it hangs at extracting Tagui

### ISSUE THREAD

**Issue by AshikinRohaime** [open-rpa/node-red-contrib-tagui#5]
msg : string[16]
"Extracting TagUI
![prob](https://user-images.githubusercontent.com/92508254/137266301-c9c062c8-132f-47b3-91bb-b300708aff1b.jpg)
" 

![image](https://user-images.githubusercontent.com/92508254/137274245-0be643e4-41b7-4705-9885-b5b07d9fbfba.png)

**Comment by AshikinRohaime** [comment]
my issues solved. There is an extra 0 byte folder named TagUI in my directory of C:\Users\user . Then after deleting it, the sample flows works well. Node-red seems confused to unzip the tagui file because there is an 0 byte tagui folder.

**Comment by skadefro** [comment]
Glad you found the solution. :-)
